test/tools: direct include for boost::replace_all definition
The boost::replace_all method is used in test/tools.h and available
via an indirect inclusion from boost/units/detail/utility.hpp.  The
replace_all method is defined in boost/algorithm/string/replace.hpp.
However, in newer versions of boost (at least 1.57) the replace.hpp
header is no longer included in the utility header and results in a
compile failure:

error: 'replace_all' is not a member of 'boost'

Fix this by directly, and appropriately, including the
boost/algorithm/string/replace.hpp header file in test/tools.h.

Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>